# Generated by Django 4.0.1 on 2022-01-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
